name: Auto Build  # 工作流名称

on:
  push:
    branches:
      - main    # 只有 main 分支的 push 事件会触发工作流

# 工作流的任务
jobs:
  build:
    runs-on: ubuntu-latest  # 使用 GitHub 托管的 Ubuntu 环境
    
    steps:
      - name: Checkout code  # 检出代码
        uses: actions/checkout@v3
      
      - name: Set up Node.js  # 设置 Node.js 环境
        uses: actions/setup-node@v3
        with:
          node-version: 20
      
      - name: Install dependencies  # 安装依赖
        run: npm i -g pnpm && pnpm install
      
      - name: Build application  # 构建应用
        run: pnpm build

  # 这是 rollback 任务，仅在 build 任务失败时执行
  # 若 build 任务成功，则该任务不会被执行
  rollback:
    needs: build
    if: ${{ failure() }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: main
          token: ${{ secrets.PAT_TOKEN }}  # 使用有写入权限的 token
      
      - name: 获取上一个提交哈希
        id: previous_commit
        run: |
          PREVIOUS_COMMIT=$(git rev-parse HEAD~1)
          echo "previous_commit=$PREVIOUS_COMMIT" >> $GITHUB_ENV
      
      - name: 创建回滚分支
        run: |
          git checkout -b rollback-${{ github.run_number }}
          git reset --hard ${{ env.previous_commit }}  # 回退到上一个提交
          git push -f origin rollback-${{ github.run_number }}  # 强制推送到新分支
      
      - name: 创建 Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.PAT_TOKEN }}
          branch: rollback-${{ github.run_number }}
          base: main
          title: "Rollback: ${{ github.event.head_commit.message }}"
          body: |
            自动回滚因构建失败触发。
            回滚到提交: ${{ env.previous_commit }}
          reviewers: DuHuiXiao  # 指定审核人